apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080