name: Backend Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["backend/**"]
  pull_request:
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build backend --tag nexlab-gitops-app-backend:$(date +%s)
