name: Frontend Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["frontend/**"]
  pull_request:
    branches: ["main"]
    paths: ["frontend/**"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          IMAGE=${{secrets.REGISTRY_LOGIN_SERVER}}/nexlab-gitops-app-frontend
          docker build frontend -t $IMAGE:${{ github.sha }} -t $IMAGE:develop
          docker push -a $IMAGE
