name: Frontend Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["frontend/**"]
  pull_request:
    branches: ["main"]
    paths: ["frontend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build frontend --tag nexlab-flux-frontend:$(date +%s)
