replicaCount: 2

image:
  repository: nexlabgitopsdemo.azurecr.io
  name: nexlab-gitops-app-frontend
  tag: develop
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts: []
  tls: []
